### ISSUE TITLE
EPIC: Routing and redirects

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/example-storefront#402]
Routing and redirect handling within the starterkit with data provided from the API/GUI in reaction.

#### Starterkit

- [ ] Allow for classic full page reload app functionality, with the ability to override for specific routes
- [ ] Fetch routes from API and apply redirects with an express middleware

#### GraphQL 

- [ ] Build GraphQL endpoints for fetching a full redirect manifest, as well as a single redirect entry

#### Functional Requirements

- [ ] Determine the gaps in functionality between what we support and what we don't but need to support.
- [ ] Determine the requirements of a Admin UI to allow route and redirect management

#### Design/Admin UI

- [ ] Present design direction for route management based on requirements
