### ISSUE TITLE
ADR & repo docs audit & update

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/example-storefront#440]
Type: **major**

**Describe the bug**
This repo's docs & decisions records haven't been updated in a few months and several recent changes/features haven't been documented.

**Sections to audit**
- [ ] `docs/testing.md`this info might be covered in our official Reaction docs.
- [ ] `docs/MobX.md` missing new "stores"
- [ ] `docs/utillites.md` very old

**Missing ADR/Docs**
- [ ] Routing: nextJS, next-routes, `src/routes.js`, MobX routerStore & express all have a hand in the apps routing. How and why these fit together?
- [ ] Auth: Passport, express, cookies & routes. What's going on in that `src/server.js` file?
- [ ] Build Process: How, when & why of the build steps.
- [ ] Payment Methods / Stripe: Similar to the [tracking events docs](https://github.com/reactioncommerce/reaction-next-starterkit/blob/develop/docs/tracking-events.md), the why & how of Stripe and possibly a naive custom payment method example.
- [ ] Starter Kit Components: Create component docs like the [Breadcrumb docs](https://github.com/reactioncommerce/reaction-next-starterkit/blob/develop/docs/components/breadcrumbs.md) for starter kit only components.
